site_name: SQL-query basics
site_description: курс по основам SQL для запроса данных


docs_dir: docs
theme:
  name: material
  icon:
    logo: material/database
  font:
    text: Roboto
    code: Roboto Mono
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  hide:
    - navigation
    - toc
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue grey
      accent: light blue
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue grey
      accent: light blue

nav:
  - Информация о курсе: index.md
  - Знакомство с данными: looking_at_your_data.md
  - Использование WHERE для выбора данных: selecting_data_subsets.md
  - Способы форматирования результатов запроса: formatting_selected_data.md
  - Агрегация данных: summarizing_your_data.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pyshkovni
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCFl8u5LGFv0UqhfP5whEoVA
    - icon: fontawesome/brands/telegram
      link: https://t.me/pyshkovni
    - icon: fontawesome/brands/vk
      link: https://vk.com/pyshkovni

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2024 <a href="https://github.com/pyshkovni"  target="_blank" rel="noopener">Nikita Pyshkov</a>